### ISSUE TITLE
Error: Cannot find module 'ts-node'

### ISSUE THREAD

**Issue by runia1** [prisma/nexus-prisma#101]
### Description

When running `npx prisma generate` I'm getting the following error:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
✔ Generated Prisma Client (2.28.0-dev.5) to ./node_modules/@prisma/client in 130ms

Error: Cannot find module 'ts-node'
Require stack:
- /Users/mar/NodeJSProjects/flightarrange/node_modules/nexus-prisma/dist/generator/gentime/settingsLoader.js
- /Users/mar/NodeJSProjects/flightarrange/node_modules/nexus-prisma/dist/cli/nexus-prisma.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.loadUserGentimeSettings (/Users/mar/NodeJSProjects/flightarrange/node_modules/nexus-prisma/dist/generator/gentime/settingsLoader.js:9:20)
    at Object.onGenerate (/Users/mar/NodeJSProjects/flightarrange/node_modules/nexus-prisma/dist/cli/nexus-prisma.js:41:26)
    at LineStream.<anonymous> (/Users/mar/NodeJSProjects/flightarrange/node_modules/@prisma/generator-helper/dist/generatorHandler.js:13:46)
    at LineStream.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
```

### Repro Steps/Link

package.json
```
{
    "dependencies": {
        "@prisma/client": "^2.27.0",
        "graphql": "^15.5.1",
        "nexus": "^1.1.0",
        "nexus-prisma": "^0.29.1"
    },
    "devDependencies": {
        "prisma": "^2.27.0"
    }
}
```

### Proposed resolution

Adding ts-node fixed the issue but I'm assuming this package should have ts-node listed under `dependencies` rather than as a `devDependency`.

**Comment by jasonkuhrt** [comment]
Related to #111
